set_property PACKAGE_PIN W5 [get_ports clk]       
 set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]



set_property PACKAGE_PIN V17 [get_ports {clear}]
set_property IOSTANDARD LVCMOS33 [get_ports {clear}]
set_property PACKAGE_PIN V16 [get_ports {oynat}]
set_property IOSTANDARD LVCMOS33 [get_ports {oynat}]
set_property PACKAGE_PIN W16 [get_ports {kaydet}]
set_property IOSTANDARD LVCMOS33 [get_ports {kaydet}]


set_property PACKAGE_PIN R2 [get_ports {switch[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[0]}]
set_property PACKAGE_PIN T1 [get_ports {switch[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[1]}]
set_property PACKAGE_PIN U1 [get_ports {switch[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[2]}]
set_property PACKAGE_PIN R3 [get_ports {switch[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[3]}]
set_property PACKAGE_PIN W2 [get_ports {switch[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[4]}]
set_property PACKAGE_PIN V2 [get_ports {switch[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[5]}]
set_property PACKAGE_PIN T3 [get_ports {switch[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[6]}]
set_property PACKAGE_PIN T2 [get_ports {switch[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[7]}]

set_property PACKAGE_PIN A14 [get_ports {servo_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {servo_out[0]}]
set_property PACKAGE_PIN A16 [get_ports {servo_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {servo_out[1]}]
set_property PACKAGE_PIN B15 [get_ports {servo_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {servo_out[2]}]
set_property PACKAGE_PIN B16 [get_ports {servo_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {servo_out[3]}]
set_property PACKAGE_PIN A15 [get_ports {servo_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {servo_out[4]}]
set_property PACKAGE_PIN K17 [get_ports {servo_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {servo_out[5]}]
set_property PACKAGE_PIN M18 [get_ports {servo_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {servo_out[6]}]
set_property PACKAGE_PIN N17 [get_ports {servo_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {servo_out[7]}]
